---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-prometheus.yml"

variables:
  CONTAINER_CLIENT_IMAGE: alpine:latest
  WOOB_BANK_MODULE: $WOOB_BANK_MODULE
  WOOB_BANK_NAME: $WOOB_BANK_NAME
  WOOB_BANK_LOGIN: $WOOB_BANK_LOGIN
  WOOB_BANK_PASSWORD: $WOOB_BANK_PASSWORD

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean
